name: Build and Test Docker App

on:
  push:
    branches: [main]  # or 'master' if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t rayfire88/app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 rayfire88/app

      - name: Test app is running
        run: |
          sleep 3  # wait for server to start
          curl http://localhost:5000 || true
